### ISSUE TITLE
Fix href in HTML link tag

### ISSUE THREAD

**Issue by Olanrewaju-dev** [mishael-codes/res-navbar#1]
Hi 👋 

What a lovely work you've done here.

I'll like to contribute to this project by fixing the href in the HTML link tag. It is a simple renaming of the names of the stylesheet in the HTML href link tag and the src attribute in the script tag within the same HTML. See the screenshot below.

<img width="1112" alt="Screenshot 2023-08-03 at 5 03 10 PM" src="https://github.com/mishael-codes/res-navbar/assets/68606513/910ab1a5-f8ff-48db-bc6a-d7d4eb4c0958">

**Comment by mishael-codes** [comment]
Hello 👋,

Thank you for your kind words! I am delighted to hear that you appreciate my work.

Your contribution sounds valuable, and I encourage you to go ahead with the fix for the href in the HTML link tag and the src attribute in the script tag. Your efforts in ensuring the correct naming of the stylesheet and script files are highly appreciated.

If you encounter any issues or need any assistance during the process, feel free to reach out. I look forward to your contribution and thank you in advance for your support in improving my project.
